name: my-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run linter
        # Run Linter
        run: make lint
      # Publish code coverage on Code Climate
      # https://github.com/paambaati/codeclimate-action
      # NOTE: uncomment for using workflow
      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v5
      #   # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true